---
title: "Nonparametric serial interval estimation with uniform mixtures"
output: github_document
author: Oswaldo Gressani
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Reproducibility instructions

This repository contains all the routines required to reproduce the results of the article “Nonparametric serial interval estimation with uniform mixtures” by Oswaldo Gressani and Niel Hens. [https://doi.org/10.1371/journal.pcbi.1013338](https://doi.org/10.1371/journal.pcbi.1013338). 

This repository is organized in three main folders (**01-Simulations**, **02-RealData** and **03-Figures**). 

- **01-Simulations** can be used to recover the results from the simulation study.

- **02-RealData** can be used to recover results related to real data applications.

- **03-Figures** can be used to recover the Figures in the article.

Readers and users are encouraged to reproduce the results contained in this folder. 
The EpiDelays package (version 0.0.1) will be needed and can be installed from the GitHub repository
[https://github.com/oswaldogressani/EpiDelays](https://github.com/oswaldogressani/EpiDelays).

### Repository version
This is version 0.0.3 (2025-09-01) - “SIEpiDelays-V3”.

### License
GPL-3.0 

### Funding statement
OG and NH were supported by the VERDI project (101045989) and the ESCAPE project (101095619), funded by the European Union. Views and opinions expressed are however those of the authors only and do not necessarily reflect those of the European Union or European Health and Digital Executive Agency (HADEA). Neither the European Union nor the granting authority can be held responsible for them. OG and NH acknowledge the financial support of the Fondation Universitaire de Belgique (file nr. AS-0608). OG and NH were also supported by the BE-PIN project (contract nr. TD/231/BE-PIN) funded by BELSPO (Belgian Science Policy Office) as part of the POST-COVID programme. The funders had no role in study design, data collection and analysis, decision to publish, or preparation of the manuscript.